services:
  - type: web
    name: vedic-backend
    env: python
    plan: free
    region: oregon
    buildCommand: |
      chmod +x backend/download_ephe.sh
      ./backend/download_ephe.sh
      pip install -r backend/requirements.txt
    startCommand: "PYTHONPATH=/app/backend python backend/run_api.py"
    envVars:
      - key: SWEPH_PATH
        value: /app/backend/astrology/ephe
      - key: GEMINI_API_KEY
        sync: false  # This will be set manually in Render dashboard 