services:
  - type: web
    name: vedic-backend
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/run_api.py"
    envVars:
      - key: SWEPH_PATH
        value: ./backend/astrology/ephe
      - key: GEMINI_API_KEY
        sync: false  # This will be set manually in Render dashboard 