services:
  - type: web
    name: vedic-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false  # This will be set manually in Render dashboard 